=== akash3699/cdac_data/html/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="invoice">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="billno" type="xs:integer"/>
        <xs:element ref="items"/>
        <xs:element name="total" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType  >
  </xs:element>
  <xs:element name="items" >
    <xs:complexType >
      <xs:sequence>
        <xs:element name="item" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== akash3699/cdac_data/html/invoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<invoice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/sunbeam/Assignment/html/invoice.xsd">
<billno>1</billno>
<items>
<item>Pizza</item>
<item>Vaada Paw</item>
<item>Misal</item>
<item>Bhel</item>
</items>
<total>300</total>
</invoice>
